name: maven central 배포
on:
  workflow_call:
    secrets:
      GPG_SECRET:
        required: true
      GPG_PASSPHRASE:
        required: true
      MAVEN_CENTRAL_USERNAME:
        required: true
      MAVEN_CENTRAL_PASSWORD:
        required: true
jobs:
  publish-to-mavencentral:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v6
      - name: Install JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Prepare Gradle Addon
        uses: gradle/gradle-build-action@v3
      - name: Build Project
        run: |
          chmod +x gradlew
          ./gradlew --stacktrace build
      - name: Publish to Maven Central
        env:
          GPG_SECRET: ${{ secrets.GPG_SECRET }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_CENTRAL_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_CENTRAL_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        run: |
          ./gradlew --stacktrace kooma-core:publish \
            -Pgpg.secret="$GPG_SECRET" \
            -Pgpg.passphrase="$GPG_PASSPHRASE" \
            -PmavenCentralUsername="$MAVEN_CENTRAL_USERNAME" \
            -PmavenCentralPassword="$MAVEN_CENTRAL_PASSWORD"